### ISSUE TITLE
Exit messages on stop workers failure

### ISSUE THREAD

**Issue by eloycoto** [RedHatInsights/yggdrasil#71]
Hi, 

On current main branch, I'm getting the following error message, a bit repetitive: 

```
[yggd] 2022/02/11 18:15:07 /home/eloy/dev/upstream/project-flotta/yggdrasil/cmd/yggd/main.go:189: starting yggd version
cannot stop workers: cannot stop worker: cannot stop worker: cannot stop process: os: process already finished
exit status 1
```

Regards

**Comment by subpop** [comment]
Yea, it's repetitive because each error handler as it unwraps up from the function where it originated adds its own error text description. In this case, it sounds like there's some redundant messaging. Are you concerned about getting the error message at all? Or just the message text being repetitive?

**Comment by eloycoto** [comment]
Message being repetitive is not great :-)
